Add: handler time page
kopo4eweb/test_rack_app pull request #1
Opened 2021-01-29 17:54 UTC by kopo4eweb

2021-01-29 19:31 UTC, BubuntuClu requested changes

2021-01-29 19:31 UTC, BubuntuClu commented on time_page.rb
> +class TimePage
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2021-01-29 19:31 UTC, BubuntuClu commented on time_page.rb
> +    [status, headers, body]
для ответа используй Rack::Response. сделай отдельный метод для ответа

2021-01-29 19:31 UTC, BubuntuClu commented on time_page.rb
> +  def initialize
тут вообще не понядобятся переменные инстанса. все делается на обычных переменных. надо правильно организовать код и передавать параметры

2021-01-29 19:31 UTC, BubuntuClu commented on time_page.rb
> +      case arg
выглядит как хэш

2021-01-29 19:31 UTC, BubuntuClu commented on time_page.rb
> +    @status = 200
почему 200?

2021-01-31 13:12 UTC, kopo4eweb commented on time_page.rb
> +    @status = 200
https://www.rubydoc.info/gems/rack/Rack/Response - решил, что раз тут используется по умолчанию статус 200, то и я могу использовать.

2021-01-31 13:13 UTC, kopo4eweb commented on time_page.rb
> +      case arg
ага, вначале не додумался, а потом как дошло :) Спс!

2021-01-31 13:14 UTC, kopo4eweb commented on time_page.rb
> +    [status, headers, body]
сделал

2021-01-31 13:14 UTC, kopo4eweb commented on time_page.rb
> +  def initialize
вроде получилось

2021-01-31 13:14 UTC, kopo4eweb commented on time_page.rb
> +class TimePage
Спасибо!

2021-01-31 18:49 UTC, BubuntuClu approved these changes

2021-01-31 18:49 UTC, BubuntuClu commented on app.rb
> +    time_formatter_res = TimeFormatter.checking_args(args)
```
tf = TimeFormatter.new(args)
tf.call

if tf.success?
    response(200, tf.time_string)
else
    response(400, tf.invalid_params)
end
```

2021-01-31 18:49 UTC, BubuntuClu commented on app.rb
> +      response(200, TimeFormatter.new.call(time_formatter_res[:correсt]))
вызывать инстанс класса с параметрами от метода класса этого класса... шота тут такой водоворот событий)

2021-02-01 09:10 UTC, merged